d3
.select('body')
.data([5, 6, 2, 8, 4, 9, 1])
.enter()
.append('div')
.text(d => d)
.style('padding', '1em')
.style('background-color', 'red')
.style('margin', '1px')
.style('width', d => `${d / 10 * 100}%`)
